
####################################################################################
# Generated by PlanAhead 14.7 built on 'Fri Sep 27 19:24:36 MDT 2013' by 'xbuild'
####################################################################################


####################################################################################
# Constraints from file : 'Sword_Original.ucf'
####################################################################################

############################################################################
# Timing constraints                                                       #
############################################################################

# NET "CLK"                                      TNM_NET = TM_CLK ;
# TIMESPEC TS_CLKIN                               = PERIOD "TM_CLK"       20 ns HIGH 50%;
    
# NET "*s_SYS_CLK"                               TNM_NET = TM_SYS_CLK;
# TIMESPEC TS_SYS_CLK                             = PERIOD "TM_SYS_CLK"   10 ns HIGH 50%;
    
# NET "*s_SYS_CLK100M"                           TNM_NET = TM_CLK_100M;
# TIMESPEC TS_SYS_CLK                             = PERIOD "TM_CLK_100M"  10 ns HIGH 50%;
    
# NET "*s_SYS_CLK50M"                            TNM_NET = TM_CLK_50M ;
# TIMESPEC TS_CLK_50M                             = PERIOD "TM_CLK_50M"   20 ns HIGH 50%;
    
# NET "*s_SYS_CLK375M"                           TNM_NET = TM_CLK_250M ;
# TIMESPEC TS_CLK_375M                            = PERIOD "TM_CLK_250M"   4 ns HIGH 50%;
    
# NET "*s_TMDS_RXC"                              TNM_NET = TM_TMDS_RXC ;
# TIMESPEC TS_TMDS_RXC                            = PERIOD "TM_TMDS_RXC"  20 ns HIGH 50%;
    
# NET "*s_UI_CLK"                                TNM_NET = TM_UI_CLK ;
# TIMESPEC TS_UI_CLK                              = PERIOD "TM_UI_CLK"     5 ns HIGH 50%;
    
# TIMESPEC "TS_100M_CLK_to_RXC_CLK"             = FROM "TM_SYS_CLK"  TO "TM_TMDS_RXC"   10 ns DATAPATHONLY ;
# TIMESPEC "TS_RXC_CLK_to_100M_CLK"             = FROM "TM_TMDS_RXC" TO "TM_SYS_CLK"    10 ns DATAPATHONLY ;
    
# TIMESPEC "TS_100M_CLK_to_50M_CLK"             = FROM "TM_SYS_CLK"  TO "TM_CLK_50M"    10 ns DATAPATHONLY ;
# TIMESPEC "TS_50M_CLK_to_100M_CLK"             = FROM "TM_CLK_50M"  TO "TM_SYS_CLK"    10 ns DATAPATHONLY ;
    
# TIMESPEC "TS_SYS_CLK_to_UI_CLK"               = FROM "TM_SYS_CLK"  TO "TM_UI_CLK"      5 ns DATAPATHONLY ;
# TIMESPEC "TS_UI_CLK_to_SYS_CLK"               = FROM "TM_UI_CLK" TO "TM_SYS_CLK"      10 ns DATAPATHONLY ;
    
# TIMESPEC "TS_UI_CLK_to_MIG_CLK"               = FROM "TM_UI_CLK"  TO "TM_MIG_CLK"      5 ns DATAPATHONLY ;
# TIMESPEC "TS_MIG_CLK_to_UI_CLK"               = FROM "TM_MIG_CLK" TO "TM_UI_CLK"       5 ns DATAPATHONLY ;
    
# NET "*XRST*"                                  TIG ;
# NET "*RST*"                                   TIG ;
    
# TIMESPEC "TS_PADS_to_FFS"                     = FROM PADS("TMDS*") TO FFS  10 ns ;
# TIMESPEC "TS_FFS_to_PADS"                     = FROM FFS TO PADS("TMDS*")  10 ns ;
    
# INST "U_HDMI_CTRL/U_LVDS_RX/U_MMCME2_ADV3/clkin1_buf"         LOC = BUFGCTRL_X0Y11 ;
# INST "U_HDMI_CTRL/U_LVDS_RX/U_MMCME2_ADV3/mmcm_adv_inst"     LOC = MMCME2_ADV_X1Y2 ;
    
############################################################################
# Location Constraints                                                     #
############################################################################
set_property PACKAGE_PIN AC18 [get_ports clk]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:50
# The conversion of 'IOSTANDARD' constraint on 'net' object 'clk' has been applied to the port object 'clk'.
set_property IOSTANDARD LVCMOS18 [get_ports clk]
set_property PACKAGE_PIN W13 [get_ports rstn]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:51
# The conversion of 'IOSTANDARD' constraint on 'net' object 'rstn' has been applied to the port object 'rstn'.
set_property IOSTANDARD LVCMOS18 [get_ports rstn]

set_property PACKAGE_PIN M24 [get_ports SEGLED_CLK]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:53
# The conversion of 'IOSTANDARD' constraint on 'net' object 'SEGLED_CLK' has been applied to the port object 'SEGLED_CLK'.
set_property IOSTANDARD LVCMOS33 [get_ports SEGLED_CLK]
set_property PACKAGE_PIN M20 [get_ports SEGLED_CLR]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:54
# The conversion of 'IOSTANDARD' constraint on 'net' object 'SEGLED_CLR' has been applied to the port object 'SEGLED_CLR'.
set_property IOSTANDARD LVCMOS33 [get_ports SEGLED_CLR]
set_property PACKAGE_PIN L24 [get_ports SEGLED_DO]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:55
# The conversion of 'IOSTANDARD' constraint on 'net' object 'SEGLED_DO' has been applied to the port object 'SEGLED_DO'.
set_property IOSTANDARD LVCMOS33 [get_ports SEGLED_DO]
set_property PACKAGE_PIN R18 [get_ports SEGLED_PEN]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:56
# The conversion of 'IOSTANDARD' constraint on 'net' object 'SEGLED_PEN' has been applied to the port object 'SEGLED_PEN'.
set_property IOSTANDARD LVCMOS33 [get_ports SEGLED_PEN]

set_property PACKAGE_PIN N26 [get_ports LED_CLK]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:58
# The conversion of 'IOSTANDARD' constraint on 'net' object 'LED_CLK' has been applied to the port object 'LED_CLK'.
set_property IOSTANDARD LVCMOS33 [get_ports LED_CLK]
set_property PACKAGE_PIN N24 [get_ports LED_CLR]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:59
# The conversion of 'IOSTANDARD' constraint on 'net' object 'LED_CLR' has been applied to the port object 'LED_CLR'.
set_property IOSTANDARD LVCMOS33 [get_ports LED_CLR]
set_property PACKAGE_PIN M26 [get_ports LED_DO]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:60
# The conversion of 'IOSTANDARD' constraint on 'net' object 'LED_DO' has been applied to the port object 'LED_DO'.
set_property IOSTANDARD LVCMOS33 [get_ports LED_DO]
set_property PACKAGE_PIN P18 [get_ports LED_PEN]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:61
# The conversion of 'IOSTANDARD' constraint on 'net' object 'LED_PEN' has been applied to the port object 'LED_PEN'.
set_property IOSTANDARD LVCMOS33 [get_ports LED_PEN]

set_property PACKAGE_PIN V17 [get_ports {BTN_X[0]}]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:63
# The conversion of 'IOSTANDARD' constraint on 'net' object 'BTN_X[0]' has been applied to the port object 'BTN_X[0]'.
set_property IOSTANDARD LVCMOS18 [get_ports {BTN_X[0]}]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:63
# The conversion of 'PULL' constraint on 'net' object 'BTN_X[0]' has been applied to the port object 'BTN_X[0]'.
set_property PULLUP true [get_ports {BTN_X[0]}]
set_property PACKAGE_PIN W18 [get_ports {BTN_X[1]}]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:64
# The conversion of 'IOSTANDARD' constraint on 'net' object 'BTN_X[1]' has been applied to the port object 'BTN_X[1]'.
set_property IOSTANDARD LVCMOS18 [get_ports {BTN_X[1]}]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:64
# The conversion of 'PULL' constraint on 'net' object 'BTN_X[1]' has been applied to the port object 'BTN_X[1]'.
set_property PULLUP true [get_ports {BTN_X[1]}]
set_property PACKAGE_PIN W19 [get_ports {BTN_X[2]}]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:65
# The conversion of 'IOSTANDARD' constraint on 'net' object 'BTN_X[2]' has been applied to the port object 'BTN_X[2]'.
set_property IOSTANDARD LVCMOS18 [get_ports {BTN_X[2]}]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:65
# The conversion of 'PULL' constraint on 'net' object 'BTN_X[2]' has been applied to the port object 'BTN_X[2]'.
set_property PULLUP true [get_ports {BTN_X[2]}]
set_property PACKAGE_PIN W15 [get_ports {BTN_X[3]}]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:66
# The conversion of 'IOSTANDARD' constraint on 'net' object 'BTN_X[3]' has been applied to the port object 'BTN_X[3]'.
set_property IOSTANDARD LVCMOS18 [get_ports {BTN_X[3]}]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:66
# The conversion of 'PULL' constraint on 'net' object 'BTN_X[3]' has been applied to the port object 'BTN_X[3]'.
set_property PULLUP true [get_ports {BTN_X[3]}]
set_property PACKAGE_PIN W16 [get_ports {BTN_X[4]}]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:67
# The conversion of 'IOSTANDARD' constraint on 'net' object 'BTN_X[4]' has been applied to the port object 'BTN_X[4]'.
set_property IOSTANDARD LVCMOS18 [get_ports {BTN_X[4]}]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:67
# The conversion of 'PULL' constraint on 'net' object 'BTN_X[4]' has been applied to the port object 'BTN_X[4]'.
set_property PULLUP true [get_ports {BTN_X[4]}]
set_property PACKAGE_PIN V18 [get_ports {BTN_Y[0]}]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:68
# The conversion of 'IOSTANDARD' constraint on 'net' object 'BTN_Y[0]' has been applied to the port object 'BTN_Y[0]'.
set_property IOSTANDARD LVCMOS18 [get_ports {BTN_Y[0]}]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:68
# The conversion of 'PULL' constraint on 'net' object 'BTN_Y[0]' has been applied to the port object 'BTN_Y[0]'.
set_property PULLUP true [get_ports {BTN_Y[0]}]
set_property PACKAGE_PIN V19 [get_ports {BTN_Y[1]}]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:69
# The conversion of 'IOSTANDARD' constraint on 'net' object 'BTN_Y[1]' has been applied to the port object 'BTN_Y[1]'.
set_property IOSTANDARD LVCMOS18 [get_ports {BTN_Y[1]}]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:69
# The conversion of 'PULL' constraint on 'net' object 'BTN_Y[1]' has been applied to the port object 'BTN_Y[1]'.
set_property PULLUP true [get_ports {BTN_Y[1]}]
set_property PACKAGE_PIN V14 [get_ports {BTN_Y[2]}]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:70
# The conversion of 'IOSTANDARD' constraint on 'net' object 'BTN_Y[2]' has been applied to the port object 'BTN_Y[2]'.
set_property IOSTANDARD LVCMOS18 [get_ports {BTN_Y[2]}]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:70
# The conversion of 'PULL' constraint on 'net' object 'BTN_Y[2]' has been applied to the port object 'BTN_Y[2]'.
set_property PULLUP true [get_ports {BTN_Y[2]}]
set_property PACKAGE_PIN W14 [get_ports {BTN_Y[3]}]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:71
# The conversion of 'IOSTANDARD' constraint on 'net' object 'BTN_Y[3]' has been applied to the port object 'BTN_Y[3]'.
set_property IOSTANDARD LVCMOS18 [get_ports {BTN_Y[3]}]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:71
# The conversion of 'PULL' constraint on 'net' object 'BTN_Y[3]' has been applied to the port object 'BTN_Y[3]'.
set_property PULLUP true [get_ports {BTN_Y[3]}]

set_property PACKAGE_PIN AA10 [get_ports {SW[0]}]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:73
# The conversion of 'IOSTANDARD' constraint on 'net' object 'SW[0]' has been applied to the port object 'SW[0]'.
set_property IOSTANDARD LVCMOS15 [get_ports {SW[0]}]
set_property PACKAGE_PIN AB10 [get_ports {SW[1]}]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:74
# The conversion of 'IOSTANDARD' constraint on 'net' object 'SW[1]' has been applied to the port object 'SW[1]'.
set_property IOSTANDARD LVCMOS15 [get_ports {SW[1]}]
set_property PACKAGE_PIN AA13 [get_ports {SW[2]}]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:75
# The conversion of 'IOSTANDARD' constraint on 'net' object 'SW[2]' has been applied to the port object 'SW[2]'.
set_property IOSTANDARD LVCMOS15 [get_ports {SW[2]}]
set_property PACKAGE_PIN AA12 [get_ports {SW[3]}]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:76
# The conversion of 'IOSTANDARD' constraint on 'net' object 'SW[3]' has been applied to the port object 'SW[3]'.
set_property IOSTANDARD LVCMOS15 [get_ports {SW[3]}]
set_property PACKAGE_PIN Y13 [get_ports {SW[4]}]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:77
# The conversion of 'IOSTANDARD' constraint on 'net' object 'SW[4]' has been applied to the port object 'SW[4]'.
set_property IOSTANDARD LVCMOS15 [get_ports {SW[4]}]
set_property PACKAGE_PIN Y12 [get_ports {SW[5]}]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:78
# The conversion of 'IOSTANDARD' constraint on 'net' object 'SW[5]' has been applied to the port object 'SW[5]'.
set_property IOSTANDARD LVCMOS15 [get_ports {SW[5]}]
set_property PACKAGE_PIN AD11 [get_ports {SW[6]}]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:79
# The conversion of 'IOSTANDARD' constraint on 'net' object 'SW[6]' has been applied to the port object 'SW[6]'.
set_property IOSTANDARD LVCMOS15 [get_ports {SW[6]}]
set_property PACKAGE_PIN AD10 [get_ports {SW[7]}]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:80
# The conversion of 'IOSTANDARD' constraint on 'net' object 'SW[7]' has been applied to the port object 'SW[7]'.
set_property IOSTANDARD LVCMOS15 [get_ports {SW[7]}]
set_property PACKAGE_PIN AE10 [get_ports {SW[8]}]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:81
# The conversion of 'IOSTANDARD' constraint on 'net' object 'SW[8]' has been applied to the port object 'SW[8]'.
set_property IOSTANDARD LVCMOS15 [get_ports {SW[8]}]
set_property PACKAGE_PIN AE12 [get_ports {SW[9]}]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:82
# The conversion of 'IOSTANDARD' constraint on 'net' object 'SW[9]' has been applied to the port object 'SW[9]'.
set_property IOSTANDARD LVCMOS15 [get_ports {SW[9]}]
set_property PACKAGE_PIN AF12 [get_ports {SW[10]}]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:83
# The conversion of 'IOSTANDARD' constraint on 'net' object 'SW[10]' has been applied to the port object 'SW[10]'.
set_property IOSTANDARD LVCMOS15 [get_ports {SW[10]}]
set_property PACKAGE_PIN AE8 [get_ports {SW[11]}]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:84
# The conversion of 'IOSTANDARD' constraint on 'net' object 'SW[11]' has been applied to the port object 'SW[11]'.
set_property IOSTANDARD LVCMOS15 [get_ports {SW[11]}]
set_property PACKAGE_PIN AF8 [get_ports {SW[12]}]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:85
# The conversion of 'IOSTANDARD' constraint on 'net' object 'SW[12]' has been applied to the port object 'SW[12]'.
set_property IOSTANDARD LVCMOS15 [get_ports {SW[12]}]
set_property PACKAGE_PIN AE13 [get_ports {SW[13]}]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:86
# The conversion of 'IOSTANDARD' constraint on 'net' object 'SW[13]' has been applied to the port object 'SW[13]'.
set_property IOSTANDARD LVCMOS15 [get_ports {SW[13]}]
set_property PACKAGE_PIN AF13 [get_ports {SW[14]}]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:87
# The conversion of 'IOSTANDARD' constraint on 'net' object 'SW[14]' has been applied to the port object 'SW[14]'.
set_property IOSTANDARD LVCMOS15 [get_ports {SW[14]}]
set_property PACKAGE_PIN AF10 [get_ports {SW[15]}]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:88
# The conversion of 'IOSTANDARD' constraint on 'net' object 'SW[15]' has been applied to the port object 'SW[15]'.
set_property IOSTANDARD LVCMOS15 [get_ports {SW[15]}]
set_property PACKAGE_PIN AF24 [get_ports buzzer]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:89
# The conversion of 'IOSTANDARD' constraint on 'net' object 'buzzer' has been applied to the port object 'buzzer'.
set_property IOSTANDARD LVCMOS33 [get_ports buzzer]



set_property PACKAGE_PIN T20 [get_ports {b[0]}]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:93
# The conversion of 'IOSTANDARD' constraint on 'net' object 'b[0]' has been applied to the port object 'b[0]'.
set_property IOSTANDARD LVCMOS33 [get_ports {b[0]}]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:93
# The conversion of 'SLEW' constraint on 'net' object 'b[0]' has been applied to the port object 'b[0]'.
set_property SLEW FAST [get_ports {b[0]}]
set_property PACKAGE_PIN R20 [get_ports {b[1]}]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:94
# The conversion of 'IOSTANDARD' constraint on 'net' object 'b[1]' has been applied to the port object 'b[1]'.
set_property IOSTANDARD LVCMOS33 [get_ports {b[1]}]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:94
# The conversion of 'SLEW' constraint on 'net' object 'b[1]' has been applied to the port object 'b[1]'.
set_property SLEW FAST [get_ports {b[1]}]
set_property PACKAGE_PIN T22 [get_ports {b[2]}]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:95
# The conversion of 'IOSTANDARD' constraint on 'net' object 'b[2]' has been applied to the port object 'b[2]'.
set_property IOSTANDARD LVCMOS33 [get_ports {b[2]}]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:95
# The conversion of 'SLEW' constraint on 'net' object 'b[2]' has been applied to the port object 'b[2]'.
set_property SLEW FAST [get_ports {b[2]}]
set_property PACKAGE_PIN T23 [get_ports {b[3]}]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:96
# The conversion of 'IOSTANDARD' constraint on 'net' object 'b[3]' has been applied to the port object 'b[3]'.
set_property IOSTANDARD LVCMOS33 [get_ports {b[3]}]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:96
# The conversion of 'SLEW' constraint on 'net' object 'b[3]' has been applied to the port object 'b[3]'.
set_property SLEW FAST [get_ports {b[3]}]
set_property PACKAGE_PIN R22 [get_ports {g[0]}]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:97
# The conversion of 'IOSTANDARD' constraint on 'net' object 'g[0]' has been applied to the port object 'g[0]'.
set_property IOSTANDARD LVCMOS33 [get_ports {g[0]}]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:97
# The conversion of 'SLEW' constraint on 'net' object 'g[0]' has been applied to the port object 'g[0]'.
set_property SLEW FAST [get_ports {g[0]}]
set_property PACKAGE_PIN R23 [get_ports {g[1]}]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:98
# The conversion of 'IOSTANDARD' constraint on 'net' object 'g[1]' has been applied to the port object 'g[1]'.
set_property IOSTANDARD LVCMOS33 [get_ports {g[1]}]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:98
# The conversion of 'SLEW' constraint on 'net' object 'g[1]' has been applied to the port object 'g[1]'.
set_property SLEW FAST [get_ports {g[1]}]
set_property PACKAGE_PIN T24 [get_ports {g[2]}]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:99
# The conversion of 'IOSTANDARD' constraint on 'net' object 'g[2]' has been applied to the port object 'g[2]'.
set_property IOSTANDARD LVCMOS33 [get_ports {g[2]}]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:99
# The conversion of 'SLEW' constraint on 'net' object 'g[2]' has been applied to the port object 'g[2]'.
set_property SLEW FAST [get_ports {g[2]}]
set_property PACKAGE_PIN T25 [get_ports {g[3]}]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:100
# The conversion of 'IOSTANDARD' constraint on 'net' object 'g[3]' has been applied to the port object 'g[3]'.
set_property IOSTANDARD LVCMOS33 [get_ports {g[3]}]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:100
# The conversion of 'SLEW' constraint on 'net' object 'g[3]' has been applied to the port object 'g[3]'.
set_property SLEW FAST [get_ports {g[3]}]
set_property PACKAGE_PIN N21 [get_ports {r[0]}]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:101
# The conversion of 'IOSTANDARD' constraint on 'net' object 'r[0]' has been applied to the port object 'r[0]'.
set_property IOSTANDARD LVCMOS33 [get_ports {r[0]}]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:101
# The conversion of 'SLEW' constraint on 'net' object 'r[0]' has been applied to the port object 'r[0]'.
set_property SLEW FAST [get_ports {r[0]}]
set_property PACKAGE_PIN N22 [get_ports {r[1]}]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:102
# The conversion of 'IOSTANDARD' constraint on 'net' object 'r[1]' has been applied to the port object 'r[1]'.
set_property IOSTANDARD LVCMOS33 [get_ports {r[1]}]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:102
# The conversion of 'SLEW' constraint on 'net' object 'r[1]' has been applied to the port object 'r[1]'.
set_property SLEW FAST [get_ports {r[1]}]
set_property PACKAGE_PIN R21 [get_ports {r[2]}]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:103
# The conversion of 'IOSTANDARD' constraint on 'net' object 'r[2]' has been applied to the port object 'r[2]'.
set_property IOSTANDARD LVCMOS33 [get_ports {r[2]}]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:103
# The conversion of 'SLEW' constraint on 'net' object 'r[2]' has been applied to the port object 'r[2]'.
set_property SLEW FAST [get_ports {r[2]}]
set_property PACKAGE_PIN P21 [get_ports {r[3]}]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:104
# The conversion of 'IOSTANDARD' constraint on 'net' object 'r[3]' has been applied to the port object 'r[3]'.
set_property IOSTANDARD LVCMOS33 [get_ports {r[3]}]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:104
# The conversion of 'SLEW' constraint on 'net' object 'r[3]' has been applied to the port object 'r[3]'.
set_property SLEW FAST [get_ports {r[3]}]
set_property PACKAGE_PIN M22 [get_ports hs]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:105
# The conversion of 'IOSTANDARD' constraint on 'net' object 'hs' has been applied to the port object 'hs'.
set_property IOSTANDARD LVCMOS33 [get_ports hs]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:105
# The conversion of 'SLEW' constraint on 'net' object 'hs' has been applied to the port object 'hs'.
set_property SLEW FAST [get_ports hs]
set_property PACKAGE_PIN M21 [get_ports vs]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:106
# The conversion of 'IOSTANDARD' constraint on 'net' object 'vs' has been applied to the port object 'vs'.
set_property IOSTANDARD LVCMOS33 [get_ports vs]
# /media/psf/Home/Nustore_Files/Nutstore/3160102142/3160102142/VGAdemo/Sword_Original.ucf:106
# The conversion of 'SLEW' constraint on 'net' object 'vs' has been applied to the port object 'vs'.
set_property SLEW FAST [get_ports vs]
############################################################################
set_property IOSTANDARD LVCMOS33 [get_ports {PS2_clk}]
set_property PACKAGE_PIN N18 [get_ports {PS2_clk}]
set_property IOSTANDARD LVCMOS33 [get_ports {PS2_data}]
set_property PACKAGE_PIN M19 [get_ports {PS2_data}]
